// <auto-generated />
using GavrilovDmitryKT_41_20.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GavrilovDmitryKT_41_20.Migrations
{
    [DbContext(typeof(SubjectDbContext))]
    [Migration("20231119120551_mr1")]
    partial class mr1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GavrilovDmitryKT_41_20.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("subject_id")
                        .HasComment("Идентификатор дисциплины");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("subject_title")
                        .HasComment("Название дисциплины");

                    b.Property<int>("TotalTime")
                        .HasColumnType("int4")
                        .HasColumnName("subject_totaltime")
                        .HasComment("Суммарное время дисциплины");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("subject_type")
                        .HasComment("Тип дисциплины");

                    b.HasKey("Id")
                        .HasName("pk_(TableName)_Id");

                    b.ToTable("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
